// frontend/src/pages/Login.tsx
import { useState } from 'react';
import { motion } from 'framer-motion';
import { LogIn } from 'lucide-react';

interface LoginProps {
  onLogin: (email: string, password: string) => Promise<void>;
}

export const Login = ({ onLogin }: LoginProps) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await onLogin(email, password);
    } catch (err) {
      setError('Invalid email or password');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#0b0f17] via-[#0f172a] to-[#020617] text-white relative overflow-hidden">
      {/* Glow Effects */}
      <div className="absolute -top-20 -left-20 w-72 h-72 bg-blue-500/20 blur-3xl rounded-full"></div>
      <div className="absolute -bottom-20 -right-20 w-72 h-72 bg-purple-500/20 blur-3xl rounded-full"></div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-sm px-6 relative z-10"
      >
        <div className="bg-[#111827]/80 backdrop-blur-xl p-8 rounded-2xl border border-white/10 shadow-xl">
          {/* Logo/Header */}
          <div className="flex justify-center mb-8">
            <div className="p-3 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 shadow-lg">
              <LogIn className="w-6 h-6 text-white" />
            </div>
          </div>

          <h1 className="text-2xl font-semibold text-center mb-2">Welcome</h1>
          <p className="text-center text-gray-400 text-sm mb-8">Sign in to your account</p>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Email Input */}
            <div>
              <label className="block text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                Email
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => {
                  setEmail(e.target.value);
                  setError('');
                }}
                placeholder="you@example.com"
                disabled={isLoading}
                className="w-full px-4 py-3 rounded-lg bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition"
              />
            </div>

            {/* Password Input */}
            <div>
              <label className="block text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                Password
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => {
                  setPassword(e.target.value);
                  setError('');
                }}
                placeholder="••••••••"
                disabled={isLoading}
                className="w-full px-4 py-3 rounded-lg bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition"
              />
            </div>

            {/* Error Message */}
            {error && (
              <div className="p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-sm">
                {error}
              </div>
            )}

            {/* Submit Button */}
            <button
              type="submit"
              disabled={isLoading || !email || !password}
              className="w-full py-3 rounded-lg bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold transition-all duration-200 hover:scale-[1.02] disabled:opacity-50 disabled:cursor-not-allowed shadow-lg"
            >
              {isLoading ? 'Signing in...' : 'Sign in'}
            </button>
          </form>

          {/* Demo Credentials */}
          <div className="mt-6 pt-6 border-t border-white/10">
            <p className="text-xs text-gray-500 text-center mb-3">Demo credentials:</p>
            <div className="space-y-2 text-xs text-gray-400">
              <p>Email: <span className="text-gray-300 font-mono">demo@example.com</span></p>
              <p>Password: <span className="text-gray-300 font-mono">demo123</span></p>
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default Login;

// frontend/src/routes/login/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { fade } from 'svelte/transition';
  import { goto } from '$app/navigation';

  let email = $state('');
  let password = $state('');
  let error = $state('');

  onMount(() => {
    const token = localStorage.getItem('token');

    if (token) goto('/dashboard');
  });

  async function handleLogin(event) {
    event.preventDefault();
    error = '';

    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}/api/auth/login`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ email, password })
      });

      if (!res.ok) {
        const text = await res.text();
        console.error(text);
        error = 'Invalid credentials. Please try again.';
        return;
      }

      const data = await res.json();

      if (data.accessToken || data.token) {
        localStorage.setItem('token', data.accessToken || data.token);
        if (data.refreshToken) {
          localStorage.setItem('refreshToken', data.refreshToken);
        }
        goto('/dashboard');
      } else {
        error = 'Login failed. Please try again.';
      }
    } catch (err) {
      console.error(err);
      error = 'Something went wrong. Please try again.';
    }
  }
</script>

<div class="auth-container">
  <div class="auth-form-section" in:fade={{ duration: 600 }}>
    <div class="form-wrapper">
      <header>
        <div class="logo-icon-generic">L</div>
        <h1>Secure access</h1>
        <p>Enter your credentials to continue</p>
      </header>

      <form on:submit|preventDefault={handleLogin}>
        <div class="input-group">
          <label for="email">User email</label>
          <input type="email" id="email" bind:value={email} placeholder="you@email.com" required />
        </div>

        <div class="input-group">
          <div class="label-row">
            <label for="password">System password</label>
            <a href="/forgot" class="forgot-link">Recover access?</a>
          </div>
          <input type="password" id="password" bind:value={password} placeholder="••••••••" required />
        </div>

        {#if error}
          <div class="error" transition:fade={{ duration: 200 }}>{error}</div>
        {/if}

        <button type="submit" class="btn-primary">Login</button>
      </form>
    </div>
  </div>

  <div class="auth-visual-section" in:fade={{ duration: 400 }}>
    <div class="background-texture-overlay"></div>
    <div class="graphic-orb orb-one"></div>
    <div class="graphic-orb orb-two"></div>
    <div class="graphic-grid"></div>
  </div>
</div>

<style>
  .auth-container {
    display: flex;
    min-height: 100vh;
    background: #ffffff;
  }

  .auth-form-section {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 60px;
  }

  .form-wrapper {
    width: 100%;
    max-width: 420px;
  }

  header {
    margin-bottom: 40px;
  }

  .logo-icon-generic {
    width: 48px;
    height: 48px;
    background: rgba(59, 130, 246, 0.1);
    color: #3b82f6;
    border-radius: 12px;
    display: grid;
    place-items: center;
    font-weight: 700;
    font-size: 1.15rem;
    margin-bottom: 24px;
    border: 1px solid rgba(59, 130, 246, 0.2);
  }

  h1 {
    font-size: 2rem;
    color: #0f172a;
    margin: 0 0 10px 0;
    font-weight: 700;
    letter-spacing: -0.01em;
  }

  header p {
    color: #64748b;
    font-size: 1rem;
    line-height: 1.5;
  }

  .input-group {
    margin-bottom: 24px;
  }

  .label-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 8px;
  }

  label {
    display: block;
    font-size: 0.9rem;
    font-weight: 600;
    color: #475569;
  }

  input {
    width: 100%;
    padding: 14px 18px;
    border: 1px solid #e2e8f0;
    border-radius: 10px;
    font-size: 1rem;
    transition: all 0.2s;
    outline: none;
    color: #1e293b;
    background: #f8fafc;
  }

  input:focus {
    border-color: #3b82f6;
    background: #ffffff;
    box-shadow: 0 0 0 4px rgba(59, 130, 246, 0.1);
  }

  .btn-primary {
    width: 100%;
    padding: 14px;
    background: #0f172a;
    color: white;
    border: none;
    border-radius: 10px;
    font-weight: 600;
    font-size: 1rem;
    cursor: pointer;
    transition: background 0.2s, transform 0.1s;
    margin-top: 10px;
  }

  .btn-primary:hover {
    background: #1e293b;
  }

  .btn-primary:active {
    transform: scale(0.99);
  }

  .error {
    background: #fee2e2;
    color: #991b1b;
    border: 1px solid #fecaca;
    padding: 10px;
    border-radius: 8px;
    font-size: 0.875rem;
    margin-bottom: 10px;
  }

  .forgot-link {
    color: #64748b;
    text-decoration: none;
    font-size: 0.85rem;
    font-weight: 500;
  }

  .forgot-link:hover {
    color: #3b82f6;
  }

  .auth-visual-section {
    flex: 1.3;
    background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 80px;
    color: white;
    overflow: hidden;
  }

  .background-texture-overlay {
    position: absolute;
    inset: 0;
    background-image:
      radial-gradient(circle at 25% 20%, rgba(148, 163, 184, 0.16), transparent 34%),
      radial-gradient(circle at 80% 70%, rgba(59, 130, 246, 0.12), transparent 32%);
  }

  .graphic-orb {
    position: absolute;
    border-radius: 50%;
    border: 1px solid rgba(148, 163, 184, 0.25);
    box-shadow: inset 0 0 24px rgba(148, 163, 184, 0.08);
  }

  .orb-one {
    width: 320px;
    height: 320px;
    top: 18%;
    right: 12%;
    background: radial-gradient(circle at 30% 30%, rgba(203, 213, 225, 0.16), rgba(15, 23, 42, 0.02));
  }

  .orb-two {
    width: 220px;
    height: 220px;
    bottom: 14%;
    left: 14%;
    background: radial-gradient(circle at 65% 35%, rgba(59, 130, 246, 0.18), rgba(30, 41, 59, 0.03));
  }

  .graphic-grid {
    position: absolute;
    inset: 12%;
    border-radius: 24px;
    border: 1px solid rgba(148, 163, 184, 0.16);
    background-image:
      linear-gradient(rgba(148, 163, 184, 0.07) 1px, transparent 1px),
      linear-gradient(90deg, rgba(148, 163, 184, 0.07) 1px, transparent 1px);
    background-size: 24px 24px;
    backdrop-filter: blur(1px);
  }

  @media (max-width: 1000px) {
    .auth-visual-section {
      display: none;
    }

    .auth-form-section {
      padding: 40px;
    }
  }

  @media (max-width: 480px) {
    .form-wrapper {
      max-width: 100%;
    }

    h1 {
      font-size: 1.6rem;
    }
  }
</style>
