// student-manager-react/src/components/StudentCard.tsx
import { Trash2, Edit2 } from "lucide-react";
import type { Student } from "../types";

interface Props {
  student: Student;
  onDelete: (id: number) => void;
  onEdit: (student: Student) => void;
}

export default function StudentCard({ student, onDelete, onEdit }: Props) {
  return (
    <div className="p-5 rounded-lg bg-gradient-to-br from-slate-700/50 to-slate-800/30 border border-slate-600/50 hover:border-slate-500 hover:shadow-lg transition-all duration-300 group">
      <div className="flex items-start justify-between mb-4">
        <div className="flex-1">
          <h3 className="text-lg font-bold text-white group-hover:text-blue-400 transition">
            {student.name}
          </h3>
          <p className="text-sm text-slate-400 mt-1">ID: {student.id}</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => onEdit(student)}
            className="p-2.5 rounded-lg bg-blue-500/10 text-blue-400 hover:bg-blue-500/20 hover:text-blue-300 transition-all duration-200 transform hover:scale-110"
            title="Edit student"
          >
            <Edit2 size={18} />
          </button>
          <button
            onClick={() => onDelete(student.id)}
            className="p-2.5 rounded-lg bg-red-500/10 text-red-400 hover:bg-red-500/20 hover:text-red-300 transition-all duration-200 transform hover:scale-110"
            title="Delete student"
          >
            <Trash2 size={18} />
          </button>
        </div>
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between p-3 rounded-lg bg-slate-900/50">
          <span className="text-sm font-medium text-slate-400">Age</span>
          <span className="text-lg font-semibold text-blue-400">{student.age} years</span>
        </div>
        <div className="flex items-center justify-between p-3 rounded-lg bg-slate-900/50">
          <span className="text-sm font-medium text-slate-400">Course</span>
          <span className="text-lg font-semibold text-indigo-400">{student.course}</span>
        </div>
      </div>
    </div>
  );
}

// frontend/src/lib/components/StudentCard.svelte
<script>
  export let student;
  export let onEdit;
  export let onDelete;
</script>

<div class="student-card">
  <div class="card-header">
    <div class="info">
      <h3>{student.name}</h3>
      <p>{student.course} • ID: {student.studentId}</p>
    </div>
    <div class="gpa-badge" class:low={student.gpa < 2.0}>
      {student.gpa.toFixed(2)}
    </div>
  </div>

  <div class="card-footer">
    <button class="btn-secondary" on:click={() => onEdit(student)}>Edit</button>
    <button class="btn-danger" on:click={() => onDelete(student._id)}>Delete</button>
  </div>
</div>

<style>
  .student-card {
    background: white;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    padding: 1.5rem;
    transition: transform 0.2s, box-shadow 0.2s;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    gap: 1.5rem;
  }

  .student-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05);
  }

  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }

  h3 {
    margin: 0;
    font-size: 1.1rem;
    color: #0f172a;
  }

  p {
    margin: 4px 0 0;
    font-size: 0.875rem;
    color: #64748b;
  }

  .gpa-badge {
    background: #dcfce7;
    color: #166534;
    padding: 4px 10px;
    border-radius: 999px;
    font-size: 0.75rem;
    font-weight: 700;
  }

  .gpa-badge.low {
    background: #fee2e2;
    color: #991b1b;
  }

  .card-footer {
    display: flex;
    gap: 0.75rem;
  }

  button {
    flex: 1;
    padding: 0.5rem;
    border-radius: 6px;
    font-size: 0.875rem;
    cursor: pointer;
    font-weight: 500;
    border: 1px solid transparent;
    transition: 0.2s;
  }

  .btn-secondary {
    background: #f1f5f9;
    color: #475569;
  }

  .btn-secondary:hover {
    background: #e2e8f0;
  }

  .btn-danger {
    background: white;
    color: #ef4444;
    border-color: #fecaca;
  }

  .btn-danger:hover {
    background: #fef2f2;
  }
</style>
